pacilboard/urls.py
from django.urls import path
from . import views

app_name = 'pb'

urlpatterns = [
    path('', views.index, name='index'),
    path('confirm/<int:confirm>', views.confirm, name='confirm'),
    path('color/<int:id>', views.color, name='color')
]

story7/urls.py
from django.contrib import admin
from django.urls import path, include

import pacilboard.urls as pacilboard
import story8.urls as story8
import story9.urls as story9
import story10.urls as story10


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(pacilboard, namespace="pb")),
    path('story8/', include(story8, namespace="story8")),
    path('story9/', include(story9, namespace="story9")),
    path('story10/', include(story10, namespace="story10"))
]

pacilboard/models.py
from django.db import models

# Create your models here.
class StatusMessage(models.Model):
    name = models.CharField(max_length=20)
    msg = models.TextField()
    color = models.CharField(max_length=20, default="burlywood")

snippet = [
        ["Night time sharpens, heightens each sensation",
        "Darkness wakes and stirs imagination",
        "Silently, the senses abandon their defenses"],

        ["Slowly, gently, night unfurls its splendor",
        "Grasp it, sense it, tremulous and tender",
        "Hearing is believing, music is deceiving",
        "Hard as lightening, soft as candlelight",
        "Dare you trust the music of the night?"],

        ["Close your eyes for your eyes will only tell the truth",
        "And the truth isn't what you want to see",
        "In the dark it is easy to pretend",
        "That the truth is what it ought to be"],

        ["Softly, deftly, music shall caress you",
        "Hear it, feel it secretly possess you",
        "Open up your mind, let your fantasies unwind",
        "In this darkness which you know you cannot fight",
        "The darkness of the music of the night"],

        ["Close your eyes",
        "Start a journey to a strange new world",
        "Leave all thoughts of the world you knew before"],

        ["Let the dream begin,", "let your darker side give in"],

        ["I'm here, nothing can harm you",
        "My words will warm and calm you"],

        ["Say you love me every waking moment",
        "Turn my head with talk of summertime",
        "Say you need me with you now and always",
        "Promise me that all you say is true",
        "That's all I ask of you"],

        ["All I want is freedom",
        "A world with no more night",
        "And you, always beside me",
        "To hold me and to hide me"],

        ["Say you need me with you, here beside you",
        "Anywhere you go, let me go too"],

        ["Say you'll share with me one love, one lifetime",
        "Say the word and I will follow you."],
        
        ["Anywhere you go, let me go too",
        "Love me, that's all I ask of you"],

        ["Where in the world",
        "Have you been hiding?",
        "Really - you were perfect"],



]

pacilboard/forms.py
from django.forms import ModelForm
from django import forms
from .models import StatusMessage

class Form(ModelForm):
    class Meta:
        model = StatusMessage
        fields = '__all__'
        exclude = ['color']
        widgets = {
            'name': forms.TextInput(
				attrs={
					'class': 'form-control newmsg',
                    'id': 'form_name',
                    'placeholder': 'Enter your name',
					}
				),
            'msg': forms.Textarea(
				attrs={
					'class': 'form-control newmsg',
                    'id': 'form_message',
                    'label': 'Status Message',                    
                    'placeholder': 'What\'s on your mind?',
                    'rows': 3,
					}
				),
        }

# class Color(ModelForm):
#     class Meta:
#         model = StatusMessage
#         fields = '__all__'
#         exclude = ['name', 'msg']
#         widgets = {
#             'color': forms.TextInput(
# 				attrs={
#                     'class': 'change-color',
# 					}
# 				),
#         }

pacilboard/views.py
from django.shortcuts import render, redirect, reverse
from django.urls import resolve, reverse
from django.contrib import messages

import random

from .forms import Form
from .models import StatusMessage

# Create your views here.
def index(request):  
    status_msg = StatusMessage.objects.all()
    new_msg = Form()

    color_choice = ['burlywood', 'bisque', 'peachpuff', 'rosybrown']
    choice = color_choice[random.randint(0,3)]

    context = {
        'status_msg': status_msg,
        'new_msg': new_msg,
        'choice': choice
    }
    return render(request, 'pacilboard/index.html', context)

def confirm(request, confirm):
    # confirm == 0 (TO BE CONFIRMED)
    if request.method == 'POST':
        name = request.POST['name']
        msg = request.POST['msg']
        
        new = StatusMessage(name = name, msg = msg)
        if confirm == 0:             
            return render(request, 'pacilboard/confirm.html', {'new': new})    
        elif confirm == 1: 
            # saves new status to database and post it on the board
            new.save()
            messages.add_message(request, messages.SUCCESS, "Your message is posted.")
            return redirect(reverse('pb:index'))      
        elif confirm == 2: 
            # cancel posting 
            messages.add_message(request, messages.SUCCESS, "Your post is canceled.")
            return redirect(reverse('pb:index'))
    return render(request, 'pacilboard/confirm.html')

def color(request, id):
    box = StatusMessage.objects.get(id=id)
    color = request.POST.get("color", "")

    newbox = StatusMessage(id=id, name=box.name, msg= box.msg, color=color)
    newbox.save()
    return redirect(reverse('pb:index'))

templates/pacilboard/base.html
<!DOCTYPE html>
<html lang="en" class="dark">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>    
    <link rel="shortcut icon" href="{% static "logo-dark.png" %}" type="image/x-icon">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
    <script defer src="https://use.fontawesome.com/releases/v5.13.0/js/all.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.13.0/js/v4-shims.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static "style.css" %}">
</head>

<body>
    {% if messages %}
    <ul class="messages container mt-4 mb-0" style="list-style: none;">
        {% for message in messages %}
        <li{% if message.tags %} class="alert alert-{{ message.tags }} alert-dismissible fade show"{% endif %}>{{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </li>
        {% endfor %}
    </ul>
    {% endif %}
    <div class="container-fluid p-0">
        <div class="header text-center">
            {% block heading %}{% endblock %}
        </div>
    </div>
    
    <div class="container">
        {% block body %}{% endblock %}
    </div>
</body>
</html>

{% block script %} {% endblock %}

templates/pacilboard/confirm.html
{% extends 'pacilboard/base.html' %}


{% block title %}PacilBoard - Confirmation Page{% endblock %}

{% block body %}
<div class="text-center">
    <p>Are you sure you wanna post this?</p> 
    <div class="card w-75 mx-auto">
        <div class="card-body">
            <blockquote class="blockquote">
                <p class="message">{{new.msg}}</p>
                <footer class="blockquote-footer name">
                    {{new.name}}
                </footer>
            </blockquote>
        </div>
    </div>
    <div class="row d-flex justify-content-center">
        <form action="{% url 'pb:confirm' confirm=2 %}" method="POST" class="mt-1 mx-1">
            {% csrf_token %}
            <input type="hidden" name="name" id="form_name" value="{{new.name}}">
            <input type="hidden" name="msg" id="form_message" value="{{new.msg}}">
            <input  type="submit" class="btn btn-lg btn-outline-dark confirm" id="no" value="NO">
        </form> 
        <form action="{% url 'pb:confirm' confirm=1 %}" method="POST" class="mt-1">
            {% csrf_token %}
            <input type="hidden" name="name" id="form_name" value="{{new.name}}">
            <input type="hidden" name="msg" id="form_message" value="{{new.msg}}">
            <input  type="submit" class="btn btn-lg btn-dark confirm" id="yes" value="YES">
        </form>
    </div>
</div>
{% endblock %}

templates/pacilboard/index.html
{% extends 'pacilboard/base.html' %}
{% load static %}
{% block title %}PacilBoard - Home{% endblock %}

{% block heading %}
<h1>PacilBoard</h1>
<h3>Share your thoughts with the world.</h3>
{% endblock %}

{% block body %}
<form action="{% url 'pb:confirm' confirm=0 %}" method="POST">
    {% csrf_token %}
    <div class="w-50 mx-auto text-right">
        <div class="row m-1 w-50">{{new_msg.name}}</div>
        <div class="row m-1">{{new_msg.msg}}</div>
        <input id="submit" class="btn btn-lg btn-dark m-1" type="submit" value="Submit">
    </div>
</form>

<div class="masonry-wrapper">
    <div id="board">
        <div class="masonry">
        {% for status in status_msg %}
        <div class="card masonry-item" style="background: {{status.color}}; border-color: {{status.color}};">
            <div class="card-body">
              <form action="{% url 'pb:color' id=status.id %}" method="POST" class="">
                {% csrf_token %}
                <button type="submit" name="color" value="{{choice}}" class="btn btn-sm btn-dark float-right colorButton"></button>
              </form>
            <blockquote class="blockquote masonry-content">
                    <p class="message">{{status.msg}}</p>
                    <footer class="blockquote-footer masonry-footer name">
                        {{status.name}}
                    </footer>
                </blockquote>
            </div>
        </div>
        {% endfor %}
        </div>
    </div>
<div class="text-center masonry-footer">
    <p>Created with &#10084; with <a href="//w3bits.com/tools/masonry-generator/" target="_blank" rel="external noopener nofollow">CSS Masonry Generator</a></p>
</div>
</div><script src="//unpkg.com/imagesloaded@4/imagesloaded.pkgd.min.js"></script>
{% endblock %}

{% block script %} 
<script>
    /**
 * Set appropriate spanning to any masonry item
 *
 * Get different properties we already set for the masonry, calculate 
 * height or spanning for any cell of the masonry grid based on its 
 * content-wrapper's height, the (row) gap of the grid, and the size 
 * of the implicit row tracks.
 *
 * @param item Object A brick/tile/cell inside the masonry
 * @link https://w3bits.com/css-grid-masonry/
 */
function resizeMasonryItem(item){
  /* Get the grid object, its row-gap, and the size of its implicit rows */
  var grid = document.getElementsByClassName('masonry')[0];
  if( grid ) {
    var rowGap = parseInt(window.getComputedStyle(grid).getPropertyValue('grid-row-gap')),
        rowHeight = parseInt(window.getComputedStyle(grid).getPropertyValue('grid-auto-rows')),
        gridImagesAsContent = item.querySelector('img.masonry-content');

    /*
     * Spanning for any brick = S
     * Grid's row-gap = G
     * Size of grid's implicitly create row-track = R
     * Height of item content = H
     * Net height of the item = H1 = H + G
     * Net height of the implicit row-track = T = G + R
     * S = H1 / T
     */
    var rowSpan = Math.ceil((item.querySelector('.masonry-content').getBoundingClientRect().height+rowGap)/(rowHeight+rowGap));

    /* Set the spanning as calculated above (S) */
    item.style.gridRowEnd = 'span '+rowSpan;
    if(gridImagesAsContent) {
      item.querySelector('img.masonry-content').style.height = item.getBoundingClientRect().height + "px";
    }
  }
}

/**
 * Apply spanning to all the masonry items
 *
 * Loop through all the items and apply the spanning to them using 
 * `resizeMasonryItem()` function.
 *
 * @uses resizeMasonryItem
 * @link https://w3bits.com/css-grid-masonry/
 */
function resizeAllMasonryItems(){
  // Get all item class objects in one list
  var allItems = document.querySelectorAll('.masonry-item');

  /*
   * Loop through the above list and execute the spanning function to
   * each list-item (i.e. each masonry item)
   */
  if( allItems ) {
    for(var i=0;i>allItems.length;i++){
      resizeMasonryItem(allItems[i]);
    }
  }
}

/**
 * Resize the items when all the images inside the masonry grid 
 * finish loading. This will ensure that all the content inside our
 * masonry items is visible.
 *
 * @uses ImagesLoaded
 * @uses resizeMasonryItem
 * @link https://w3bits.com/css-grid-masonry/
 */
function waitForImages() {
  //var grid = document.getElementById("masonry");
  var allItems = document.querySelectorAll('.masonry-item');
  if( allItems ) {
    for(var i=0;i<allItems.length;i++){
      imagesLoaded( allItems[i], function(instance) {
        var item = instance.elements[0];
        resizeMasonryItem(item);
        console.log("Waiting for Images");
      } );
    }
  }
}

/* Resize all the grid items on the load and resize events */
var masonryEvents = ['load', 'resize'];
masonryEvents.forEach( function(event) {
  window.addEventListener(event, resizeAllMasonryItems);
} );

/* Do a resize once more when all the images finish loading */
waitForImages();
</script>
{% endblock %}