story7/urls.py
from django.contrib import admin
from django.urls import path, include

import pacilboard.urls as pacilboard
import story8.urls as story8
import story9.urls as story9
import story10.urls as story10


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(pacilboard, namespace="pb")),
    path('story8/', include(story8, namespace="story8")),
    path('story9/', include(story9, namespace="story9")),
    path('story10/', include(story10, namespace="story10"))
]

story9/urls.py
from django.urls import path
from . import views

app_name = 'story9'

urlpatterns = [
    path('', views.index, name='index'),
    path('like/', views.like, name='like'),
    path('top5/', views.top5, name='top5')
]

story9/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
    id = models.CharField(max_length=20, primary_key=True)
    title = models.CharField(max_length=100)
    authors = models.CharField(max_length=100)
    likes = models.IntegerField(default=1)

    def as_dict(self):
        return {
        "title": self.title,
        "authors": self.authors,
        "likes": self.likes,
        }

story9/views.py
from django.shortcuts import render, redirect, reverse
from django.http import JsonResponse
from django.urls import resolve, reverse
from django.views.decorators.csrf import csrf_exempt
from django.contrib import messages

from .models import Book


# Create your views here.
def index(request): 
    return render(request, 'story9/index.html')

@csrf_exempt
def like(request): 
    if request.method == 'POST':
        id = request.POST['id']
        title = request.POST['title']
        authors = request.POST['authors']        

        book, status = Book.objects.get_or_create(id=id, title=title, authors=authors)
        if status: 
            # book has never been liked before :(
            book.save()
        else:
            # book is liked already 
            book.likes += 1
            liked = Book(id=id, title=book.title, authors=book.authors, likes=book.likes)
            liked.save()
        return JsonResponse(book.as_dict())
        

def top5(request): 
    top5 = [book.as_dict() for book in Book.objects.order_by('-likes')[:5]]
    return JsonResponse({'top5':top5})

templates/story9/index.html
{% extends 'pacilboard/base.html' %}
{% load static %}

{% block title %}RakBooKoo{% endblock %}

{% block heading %}
<div id="notif" class="float-right" style="color: black; position: fixed; top:1rem; right: 2rem;"><i class="fas fa-thumbs-up" style="font-size: 3rem;"></i><br>Liked!</div>
<h1><i class="fas fa-book-reader"></i></h1>
<h1>RakBooKoo</h1> 
<!-- Button trigger modal -->
<button type="button" id="top5button" class="btn btn-dark" data-toggle="modal" data-target="#top5">
    Top Five Books
</button>
{% endblock %}

{% block body %}
<!-- Modal -->
    <div class="modal fade" id="top5" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" style="color: black;">Top Five Books by Readers</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            <ol id="top5content"></ol>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
<!-- End Modal -->

<input id="search" placeholder="Find interesting bookoos~" style="width: 20rem; border-radius: .2rem; border: none; line-height: 1.5; padding: .25rem .5rem;">
<button id="searchbutton" type="button" class="btn btn-light btn-sm">Search</button>

<div id="results" class="row d-flex justify-content-between"></div>
{% endblock %}

{% block script %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

<script>
     $(document).ready(function(){
        function bookSearch() {
            var search = $('#search').val();
            console.log(search);

            $.ajax({
                url: "https://www.googleapis.com/books/v1/volumes?q=" + search, 
                dataType: "json",

                success: function(data) {
                    console.log(data)
                    for (i = 0; i < data.items.length; i++) {
                        $('#results').append('<div class="card result d-flex justify-content-between align-items-center my-2 mx-auto" style="width: 13.5rem;">' + 
                        '<img class="card-img-top" src="' + data.items[i].volumeInfo.imageLinks.smallThumbnail + '"><b id="booktitle" class="card-title text-center" style="color: maroon">' +
                        data.items[i].volumeInfo.title + '</b><p id="bookauthor" class="text-center">' +
                        data.items[i].volumeInfo.authors +
                        '<button type="button" id="'+ data.items[i].id +'" title="'+ data.items[i].volumeInfo.title +'" author="'+ data.items[i].volumeInfo.authors +'" class="likebutton btn btn-sm btn-danger ml-3">Like</button></p></div>');
                    }
                },

                type: 'GET'
            });
        }

        function notif() {           
            $("#notif").css("color", "white");
            $("#notif").css("transition", "all .5s ease");
            setTimeout(function() {$("#notif").css("color", "black")}, 1000);
        }

        function likeBook(id, title, author) {
            //TO DO: implement like book ajax function
            $.ajax({
                url: "{% url "story9:like" %}", 
                data: { id: id, title: title, authors: author },

                success: function(book) {
                    console.log(book);
                    notif();                    
                },

                type: 'POST'
            });
        }

        $("#searchbutton").click(function(){
            $('#results').empty();
            bookSearch();
        });        

        $("#results").click(function(e) {
            if ($(e.target).hasClass("likebutton")){
                console.log("this func runs from button");
                var id = $(e.target).attr("id");
                var title = $(e.target).attr("title");
                var author = $(e.target).attr("author");
                console.log(id + title + author);
                likeBook(id, title, author);                 
            }                               
        });

        $("#top5button").click(function(){
            $.ajax({
                url: "{% url "story9:top5" %}", 
                dataType: "json",

                success: function(books) {
                    console.log(books);
                    $('#top5content').empty();
                    for (i in books.top5) {
                        $('#top5content').append(
                            '<li><b>' + books.top5[i].title + '</b><span> - ' + 
                            books.top5[i].authors + '</span><span class="badge badge-pill badge-danger float-right"><i class="fas fa-thumbs-up"></i>  ' + books.top5[i].likes +'</span></li>'
                        )
                    }                    
                },

                type: 'GET'
            });
        }); 
    });
</script>
{% endblock %}